# Introduction: Python

Here is a brief introduction to some python things which will be useful.

If you are familiar with python dictionaries, lists, and numpy (including arrays etc.), feel free to skip this notebook.

## Python lists

A list is one of the most fundamental data-structures. They can contain items of different types and are *ordered* (meaning if items are inputted in a specific order, they remain in this order).

Let's declare a empty list to work with:

In [1]:
our_list = [] # Declare an empty list
print(our_list)

[]


Now, let's add some things to the list:


In [2]:
our_list.append('apples') # add a string to the list
our_list.append(3)        # add an int to the list
our_list.append(5.32)     # add a float to the list

print(our_list)

['apples', 3, 5.32]


Now we can pick out elements by index:
    

In [7]:
print(our_list[0]) # this should print the '0'th element of the list


apples


## Python dictionaries

A dictionary is also a useful data structure. They can contain items of different types and are ***un-ordered***.

Let's declare a empty dictionary to work with:

In [9]:
my_dict = {}

Dictionary *items* have corresponding *keys* and to work with a particular item in a dictionary, you call it by key, not by index. Let's add a few items to the dict with the corresponding keys

In [11]:
my_dict['key1'] = 'apple'
my_dict['key2'] = 'banana'
my_dict['key3'] = 'orange'
my_dict['key4'] = 4
print(my_dict)

{'key1': 'apple', 'key2': 'banana', 'key3': 'orange', 'key4': 4}


Index an element in the dictionary by the corresponding key:

In [12]:
print(my_dict['key2'])

banana


This should have printed **banana**

We can also access all keys and items in the dict. It is useful to then convert the results to lists.


In [16]:
keys = my_dict.keys()
values = my_dict.values()

print('The keys are:', keys, '\nThe corresponding values are:', values)

keys_list = list(keys)
values_list = list(values)

print('\nThe list of keys are:', keys_list, '\nThe corresponding list of values are:', values_list)


The keys are: dict_keys(['key1', 'key2', 'key3', 'key4']) 
The corresponding values are: dict_values(['apple', 'banana', 'orange', 4])

The list of keys are: ['key1', 'key2', 'key3', 'key4'] 
The corresponding list of values are: ['apple', 'banana', 'orange', 4]


We can check if a particular value exists in the dictionary:


In [23]:
'apple' in my_dict.values() 

True

In [24]:
'apple' in values_list 

True

The above should both have given 'True'.

# Numpy Arrays
The third datastructure you will need is the numpy array.

To use the numpy array, and all the functions we need in the numpy library, 
we need to import it.

In [30]:
import numpy as np

Let's prepare a numpy 1 dimensional array with 3 floats as elements

In [41]:
our_array = np.array([3.2, 42.0, 7.3])
print(our_array)

[ 3.2 42.   7.3]


We can access elements of the array the same as python lists

In [42]:
print(our_array[1])

42.0


This should have printed [42](https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker's_Guide_to_the_Galaxy).

We can also convert python lists into numpy arrays easily.

In [43]:
array_list = [3.0, 5.6]
list_array = np.array(array_list)

print('The type of my original list is: ', type(array_list))
print('The type of my list converted into a numpy array is: ', type(list_array))


The type of my original list is:  <class 'list'>
The type of my list converted into a numpy array is:  <class 'numpy.ndarray'>


Numpy arrays can also be multi-dimensional. Let's define an array which is all zeros (for the americans) with 9 columns and 7 rows.

In [48]:
zero_array = np.zeros([7, 9])
print(zero_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


We can access the entire row also:
    

In [51]:
third_row = zero_array[2]

print(third_row)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


And also the entire column

In [55]:
second_column = zero_array[:,2]

print(second_column)

[0. 0. 0. 0. 0. 0. 0.]
